config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :fruits

  get 'get_fruits' => 'fruits#get_fruits'
  
  get 'get_fruit/:id', to: 'fruits#get_fruit'
  get 'get_categories' => 'categories#get_categories'


  get 'forbidden' => 'pages#forbidden'



end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  def get_categories
    categories = Category.all
    respond_to do |format|
        format.json { render json: {data: categories} }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, :except => 'get_fruits'
  before_action :bounce_posers, :except => 'get_fruits'

  # GET /fruits
  # GET /fruits.json
  def index
    @fruits = Fruit.all
  end

  def get_fruits
    fruits = Fruit.all
    respond_to do |format|
        format.json { render json: {data: fruits} }
    end
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
  end

  def get_fruit
    @fruit = Fruit.find(params[:id])
    respond_to do |format|
        format.json { render json: {data: @fruit} }
    end
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: 'Fruit was successfully created.' }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to @fruit, notice: 'Fruit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.html { redirect_to fruits_url, notice: 'Fruit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    def bounce_posers
      redirect_to forbidden_path unless current_admin.email == "nmuta1@gmail.com"
      # redirect_to login_path unless current_admin.email == "nmuta1@gmail.com"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruit_params
      params.require(:fruit).permit(:name, :url, :source, :price, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def forbidden
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/fruits/_form.html.erb
<%= form_with(model: fruit, local: true) do |form| %>
  <% if fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
      <% fruit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :fruit_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :fruit_url %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :fruit_source %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :fruit_price %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :fruit_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fruits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Source</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fruits.each do |fruit| %>
      <tr>
        <td><%= fruit.name %></td>
        <td><%= fruit.url %></td>
        <td><%= fruit.source %></td>
        <td><%= fruit.price %></td>
        <td><%= fruit.category_id %></td>
        <td><%= link_to 'Show', fruit %></td>
        <td><%= link_to 'Edit', edit_fruit_path(fruit) %></td>
        <td><%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fruit.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @fruit.url %>
</p>

<p>
  <strong>Source:</strong>
  <%= @fruit.source %>
</p>

<p>
  <strong>Price:</strong>
  <%= @fruit.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @fruit.category_id %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruitstand</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/forbidden.html.erb
This page is forbidden